version: "3"
volumes:
  postgres-data:
  hive-data:
  spark-data:

services:
  hive:
    build: .
    entrypoint: /init-hive.sh
    ports:
      - "9083:9083"
      - "10000:10000"
    links:
      - "postgres:postgres"
    volumes:
      - hive-data:/opt/hadoop-2.7.4/data

  spark:
    build: .
    entrypoint: /init-spark.sh
    ports:
      - "10001:10001"
    links:
      - "postgres:postgres"
      - "hive:hive"
    volumes:
      - spark-data:/opt/spark-2.4.4-bin-hadoop2.7/data

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    volumes:
      - postgres-data:/var/lib/postgresql/data
